(() => {
  const normalizeDistrictKey = (value) =>
    (value || '')
      .toString()
      .normalize('NFD')
      .replace(/[\u0300-\u036f]/g, '')
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-+|-+$/g, '');

  const DISTRICT_GUIDES = {
    ampara: {
      name: 'Ampara',
      climate: 'Warm and dry',
      weather: 'Best in May to September for east coast beaches and calm seas.',
      summary: 'Long east coast beaches, lagoons, and birdlife with quieter crowds.',
      highlights: ['Arugam Bay', 'Kumana birdlife', 'Lagoon villages'],
      focus: 'Surf, nature, beach days',
      image: 'images/26.jpeg',
    },
    anuradhapura: {
      name: 'Anuradhapura',
      climate: 'Warm and dry',
      weather: 'Dry months from May to September are easiest for site visits.',
      summary: 'Sacred ancient city with stupas, tanks, and old monastic landscapes.',
      highlights: ['Ruwanwelisaya', 'Sri Maha Bodhi', 'Mihintale day trip'],
      focus: 'History, culture, heritage',
      image: 'images/2.jpeg',
    },
    badulla: {
      name: 'Badulla',
      climate: 'Cool highlands',
      weather: 'Most pleasant in January to April and July to September.',
      summary: 'Tea-country views, rail journeys, and mountain village life.',
      highlights: ['Ella Nine Arch', 'Lipton Seat', 'Diyaluma Falls'],
      focus: 'Train routes, hiking, scenery',
      image: 'images/34.jpeg',
    },
    batticaloa: {
      name: 'Batticaloa',
      climate: 'Warm coastal',
      weather: 'Drier and sunnier from May to September.',
      summary: 'Calm beaches and lagoon culture on Sri Lanka\'s east coast.',
      highlights: ['Batticaloa lagoon', 'Dutch fort', 'Pasikuda access'],
      focus: 'Beach, lagoon, local culture',
      image: 'images/20.jpeg',
    },
    colombo: {
      name: 'Colombo',
      climate: 'Warm and humid',
      weather: 'Year-round city stop; best evenings from December to March.',
      summary: 'Gateway city with food streets, design hotels, and ocean sunsets.',
      highlights: ['Galle Face Green', 'Pettah market', 'Cafe and gallery trail'],
      focus: 'City, food, shopping',
      image: 'images/5.jpeg',
    },
    galle: {
      name: 'Galle',
      climate: 'Warm coastal',
      weather: 'Best from December to April on the southwest coast.',
      summary: 'Fort walls, boutique stays, and a relaxed ocean-side old town.',
      highlights: ['Galle Fort', 'Lighthouse coast', 'Cafe streets'],
      focus: 'Heritage, coast, slow travel',
      image: 'images/14.jpeg',
    },
    gampaha: {
      name: 'Gampaha',
      climate: 'Warm tropical',
      weather: 'Good year-round transit region with short rain spells.',
      summary: 'Airport corridor district with wetlands and easy coastal access.',
      highlights: ['Negombo lagoon', 'Fish market', 'Muthurajawela marsh'],
      focus: 'Arrival, wetlands, quick stops',
      image: 'images/11.jpeg',
    },
    hambantota: {
      name: 'Hambantota',
      climate: 'Hot and dry',
      weather: 'Strong for safari and coast from December to April.',
      summary: 'Wild southeast coast, salt flats, and safari access points.',
      highlights: ['Bundala National Park', 'Tangalle coast', 'Bird habitats'],
      focus: 'Wildlife, coast, photography',
      image: 'images/18.jpeg',
    },
    jaffna: {
      name: 'Jaffna',
      climate: 'Warm and dry',
      weather: 'Best from January to September with fewer heavy showers.',
      summary: 'Northern peninsula culture, islands, and distinct Tamil heritage.',
      highlights: ['Nallur Temple', 'Jaffna fort', 'Delft island trip'],
      focus: 'Culture, food, history',
      image: 'images/27.jpeg',
    },
    kalutara: {
      name: 'Kalutara',
      climate: 'Warm coastal',
      weather: 'Best beach windows from December to April.',
      summary: 'Southwest coastal district with river estuaries and beaches.',
      highlights: ['Kalutara beach', 'Richmond Castle', 'Bentota access'],
      focus: 'Beach, short escapes',
      image: 'images/6.jpeg',
    },
    kegalle: {
      name: 'Kegalle',
      climate: 'Warm with hills',
      weather: 'Comfortable most months except heavier monsoon spells.',
      summary: 'Gateway to rainforests and highland transitions.',
      highlights: ['Pinnawala area', 'Village landscapes', 'Forest edges'],
      focus: 'Nature, family stops',
      image: 'images/23.jpeg',
    },
    kilinochchi: {
      name: 'Kilinochchi',
      climate: 'Warm dry plains',
      weather: 'Best explored from January to September.',
      summary: 'Northern plains with reservoirs and open landscapes.',
      highlights: ['Iranamadu tank', 'Rural routes', 'Northern overland links'],
      focus: 'Road journeys, local life',
      image: 'images/31.jpeg',
    },
    kurunegala: {
      name: 'Kurunegala',
      climate: 'Warm inland',
      weather: 'Good all year with short afternoon showers.',
      summary: 'Central-west transit district with lakes and rock outcrops.',
      highlights: ['Kurunegala lake', 'Ethagala rock', 'Local food stops'],
      focus: 'Transit, viewpoints, culture',
      image: 'images/10.jpeg',
    },
    mahanuvara: {
      name: 'Mahanuvara (Kandy)',
      climate: 'Mild highland',
      weather: 'Best from January to April and July to September.',
      summary: 'Temple city and hill-country culture center.',
      highlights: ['Temple of the Tooth', 'Kandy lake', 'Peradeniya gardens'],
      focus: 'Culture, ceremony, gardens',
      image: 'images/1.jpeg',
    },
    mannar: {
      name: 'Mannar',
      climate: 'Hot and dry',
      weather: 'Dry-season travel is easiest from January to September.',
      summary: 'Quiet northwest coast known for migratory birds and open roads.',
      highlights: ['Mannar causeway', 'Baobab tree', 'Bird migration spots'],
      focus: 'Birding, quiet coast',
      image: 'images/22.jpeg',
    },
    matale: {
      name: 'Matale',
      climate: 'Warm inland',
      weather: 'Pleasant most months with short wet periods.',
      summary: 'Spice gardens and central routes near the cultural heartland.',
      highlights: ['Spice estates', 'Knuckles approaches', 'Cave temples'],
      focus: 'Spice, trekking, culture',
      image: 'images/13.jpeg',
    },
    matara: {
      name: 'Matara',
      climate: 'Warm coastal',
      weather: 'Best from December to April for beach-focused trips.',
      summary: 'South coast beaches, surf zones, and laid-back seaside towns.',
      highlights: ['Polhena beach', 'Dondra Head', 'Weligama access'],
      focus: 'Surf, beach, coast',
      image: 'images/16.jpeg',
    },
    moneragala: {
      name: 'Moneragala',
      climate: 'Warm and dry',
      weather: 'Dry months are ideal for safaris and open-road travel.',
      summary: 'Large southeastern district with wildlife corridors and forests.',
      highlights: ['Gal Oya access', 'Wild elephant zones', 'Rural landscapes'],
      focus: 'Wildlife, nature drives',
      image: 'images/28.jpeg',
    },
    mullaitivu: {
      name: 'Mullaitivu',
      climate: 'Warm coastal',
      weather: 'Best in drier months from January to September.',
      summary: 'Remote northeast coastline with long empty beaches.',
      highlights: ['Nayaru coast', 'Lagoon edges', 'Quiet drives'],
      focus: 'Remote coast, solitude',
      image: 'images/25.jpeg',
    },
    'nuwara-eliya': {
      name: 'Nuwara Eliya',
      climate: 'Cool mountain',
      weather: 'Cool year-round; clearest skies often January to April.',
      summary: 'Tea estates, colonial bungalows, and cool-weather walks.',
      highlights: ['Tea plantations', 'Gregory Lake', 'Horton Plains'],
      focus: 'Cool weather, tea, hiking',
      image: 'images/32.jpeg',
    },
    polonnaruwa: {
      name: 'Polonnaruwa',
      climate: 'Warm dry zone',
      weather: 'Best from May to September for archaeological visits.',
      summary: 'Ancient ruins surrounded by reservoirs and dry-zone forests.',
      highlights: ['Ancient city ruins', 'Gal Vihara', 'Parakrama Samudra'],
      focus: 'Archaeology, heritage',
      image: 'images/12.jpeg',
    },
    puttalam: {
      name: 'Puttalam',
      climate: 'Warm and breezy',
      weather: 'Generally dry and good for coast and kite season.',
      summary: 'Northwest coast with lagoons, dunes, and kite-surf settings.',
      highlights: ['Kalpitiya', 'Lagoon routes', 'Dolphin waters'],
      focus: 'Kite surf, coast, lagoon',
      image: 'images/9.jpeg',
    },
    ratnapura: {
      name: 'Ratnapura',
      climate: 'Warm with rainforest',
      weather: 'Greener and wetter district, best on dry windows.',
      summary: 'Gem district and rainforest gateway near Sinharaja.',
      highlights: ['Gem history', 'Sinharaja access', 'Waterfall routes'],
      focus: 'Rainforest, gems, nature',
      image: 'images/33.jpeg',
    },
    trincomalee: {
      name: 'Trincomalee',
      climate: 'Warm coastal',
      weather: 'Excellent beach season from May to September.',
      summary: 'East coast harbor town with clear-water beaches and temples.',
      highlights: ['Nilaveli beach', 'Pigeon Island', 'Koneswaram temple'],
      focus: 'Beach, snorkeling, culture',
      image: 'images/24.jpeg',
    },
    vavuniya: {
      name: 'Vavuniya',
      climate: 'Warm inland',
      weather: 'Travel friendly most months outside heavier rains.',
      summary: 'Northern gateway district on major overland routes.',
      highlights: ['Regional markets', 'Road hub', 'Cultural crossroads'],
      focus: 'Transit, local life',
      image: 'images/21.jpeg',
    },
  };

  window.normalizeDistrictKey = normalizeDistrictKey;
  window.DISTRICT_GUIDES = DISTRICT_GUIDES;
})();
